#!/bin/bash
# AndrewOS — one-command Docker start for macOS.
# No Rust, Python, or build tools needed — just Docker Desktop.
# Auto-generates your login token, builds the container, and starts the web server.
#
#   Run from inside the repo:   ./docker-start.sh
#   Or straight from the web:   curl -sSL https://raw.githubusercontent.com/Sompote/AndrewOS/main/docker-start.sh | bash
#
#   Include browser control (agent can drive a real browser; adds ~400 MB):
#     curl -sSL https://raw.githubusercontent.com/Sompote/AndrewOS/main/docker-start.sh | INSTALL_BROWSER=true bash
set -euo pipefail

REPO_URL="https://github.com/Sompote/AndrewOS.git"
PORT="${PORT:-3001}"
INSTALL_BROWSER="${INSTALL_BROWSER:-false}"

# ── Colors ──
GREEN='\033[0;32m'; BLUE='\033[0;34m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
die() { echo -e "${RED}[ERROR] $1${NC}" >&2; exit 1; }
ok()  { echo -e "${GREEN}[OK]${NC} $1"; }

echo ""
echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  AndrewOS — Docker start for macOS${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# ── 1. Check Docker ──
command -v docker &>/dev/null || die "Docker not found. Install Docker Desktop: https://docs.docker.com/desktop/install/mac-install/"
docker compose version &>/dev/null || die "Docker Compose plugin not found. Update Docker Desktop to a recent version."
if ! docker info &>/dev/null; then
    die "Docker is installed but not running. Open Docker Desktop, wait for the whale icon to settle, then re-run this script."
fi
ok "Docker is installed and running"

# ── 2. Make sure we're in the repo (clone it if we're not) ──
if [ ! -f "docker-compose.yml" ] || [ ! -f "Dockerfile" ]; then
    echo -e "${YELLOW}Not inside the AndrewOS repo — cloning it...${NC}"
    INSTALL_DIR="$HOME/AndrewOS"
    if [ -d "$INSTALL_DIR/.git" ]; then
        git -C "$INSTALL_DIR" pull --ff-only || echo -e "${YELLOW}Pull failed, using existing code.${NC}"
    else
        [ -d "$INSTALL_DIR" ] && rm -rf "$INSTALL_DIR"
        (cd "$HOME" && git clone "$REPO_URL" "$INSTALL_DIR") || die "git clone failed"
    fi
    cd "$INSTALL_DIR"
fi
ok "Repo ready at $(pwd)"

# ── 3. Set up the login token in .env ──
if [ -f ".env" ] && grep -q '^ACCESS_TOKEN=' .env && \
   ! grep -q '^ACCESS_TOKEN=change-me-to-a-long-random-secret$' .env; then
    TOKEN="$(grep '^ACCESS_TOKEN=' .env | head -n1 | cut -d= -f2-)"
    ok "Using existing token from .env"
    # Opt into browser control if requested and not already recorded.
    if [ "$INSTALL_BROWSER" = "true" ] && ! grep -q '^INSTALL_BROWSER=' .env; then
        echo "INSTALL_BROWSER=true" >> .env
        ok "Enabled browser control in .env (browser baked into the image)"
    fi
else
    TOKEN="$(openssl rand -hex 32)"
    # Write a fresh .env, preserving an optional PORT line if the user set one.
    {
        echo "# AndrewOS Docker environment — generated by docker-start.sh"
        echo "ACCESS_TOKEN=$TOKEN"
        [ "$PORT" != "3001" ] && echo "PORT=$PORT"
        [ "$INSTALL_BROWSER" = "true" ] && echo "INSTALL_BROWSER=true"
    } > .env
    chmod 600 .env 2>/dev/null || true
    ok "Generated a new login token and saved it to .env"
fi

[ "$INSTALL_BROWSER" = "true" ] && echo -e "${YELLOW}Browser control enabled — the build will download the browser (~400 MB), so the first build takes longer.${NC}"

# ── 4. Build and start ──
echo ""
echo -e "${BLUE}Building and starting the container...${NC}"
echo "First build compiles the Rust binary and may take a few minutes."
echo ""
docker compose up -d --build || die "docker compose failed. See the output above."

# ── 5. Wait for health ──
echo ""
echo -ne "${BLUE}Waiting for the server to come up...${NC}"
for _ in $(seq 1 30); do
    if curl -fsS "http://127.0.0.1:${PORT}/web" >/dev/null 2>&1; then
        echo -e " ${GREEN}ready!${NC}"
        break
    fi
    echo -n "."
    sleep 2
done
echo ""

# ── Summary ──
echo ""
echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}  AndrewOS is running!${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "  Open:   ${BLUE}http://localhost:${PORT}/web/${NC}"
echo -e "  Token:  ${YELLOW}${TOKEN}${NC}"
echo ""
echo "  (The token is saved in .env — paste it into the web UI to log in,"
echo "   then set your AI provider and API key under Settings.)"
echo ""
if [ "$INSTALL_BROWSER" = "true" ]; then
    echo -e "  ${GREEN}Browser control:${NC} browser is baked in — enable it in"
    echo "  Settings → AI / API → Browser Control (engine: Chromium)."
    echo ""
fi
echo "  Logs:   docker compose logs -f"
echo "  Stop:   docker compose down"
echo "  Start:  docker compose up -d"
echo ""

# Open the browser for convenience.
command -v open &>/dev/null && open "http://localhost:${PORT}/web/" 2>/dev/null || true
