# AndrewOS - one-command Docker start for Windows (PowerShell).
# No Rust, Python, or build tools needed - just Docker Desktop.
# Auto-generates your login token, builds the container, and starts the web server.
#
#   Run from inside the repo:   .\docker-start.ps1
#   Or straight from the web:   irm https://raw.githubusercontent.com/Sompote/AndrewOS/main/docker-start.ps1 | iex
#
#   Include browser control (agent can drive a real browser; adds ~400 MB):
#     $env:INSTALL_BROWSER='true'; irm https://raw.githubusercontent.com/Sompote/AndrewOS/main/docker-start.ps1 | iex
$ErrorActionPreference = 'Stop'

$RepoUrl = 'https://github.com/Sompote/AndrewOS.git'
$Port = if ($env:PORT) { $env:PORT } else { '3001' }
$InstallBrowser = if ($env:INSTALL_BROWSER -eq 'true') { 'true' } else { 'false' }

function Write-Ok   ($m) { Write-Host "[OK] $m"   -ForegroundColor Green }
function Write-Info ($m) { Write-Host $m          -ForegroundColor Cyan }
function Die        ($m) { Write-Host "[ERROR] $m" -ForegroundColor Red; exit 1 }

Write-Host ''
Write-Host '========================================' -ForegroundColor Blue
Write-Host '  AndrewOS - Docker start for Windows'    -ForegroundColor Blue
Write-Host '========================================' -ForegroundColor Blue
Write-Host ''

# -- 1. Check Docker --
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Die 'Docker not found. Install Docker Desktop: https://docs.docker.com/desktop/install/windows-install/'
}
try { docker compose version | Out-Null } catch {
    Die 'Docker Compose plugin not found. Update Docker Desktop to a recent version.'
}
try { docker info 2>$null | Out-Null; if ($LASTEXITCODE -ne 0) { throw } } catch {
    Die 'Docker is installed but not running. Start Docker Desktop, wait for the whale icon to settle, then re-run this script.'
}
Write-Ok 'Docker is installed and running'

# -- 2. Make sure we're in the repo (clone it if we're not) --
if (-not (Test-Path 'docker-compose.yml') -or -not (Test-Path 'Dockerfile')) {
    Write-Host 'Not inside the AndrewOS repo - cloning it...' -ForegroundColor Yellow
    if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
        Die 'git not found. Install Git for Windows: https://git-scm.com/download/win'
    }
    $InstallDir = Join-Path $HOME 'AndrewOS'
    if (Test-Path (Join-Path $InstallDir '.git')) {
        git -C $InstallDir pull --ff-only
    } else {
        if (Test-Path $InstallDir) { Remove-Item -Recurse -Force $InstallDir }
        git clone $RepoUrl $InstallDir
        if ($LASTEXITCODE -ne 0) { Die 'git clone failed' }
    }
    Set-Location $InstallDir
}
Write-Ok "Repo ready at $(Get-Location)"

# -- 3. Set up the login token in .env --
$existing = $null
if (Test-Path '.env') {
    $line = Select-String -Path '.env' -Pattern '^ACCESS_TOKEN=(.+)$' | Select-Object -First 1
    if ($line) { $existing = $line.Matches[0].Groups[1].Value }
}
if ($existing -and $existing -ne 'change-me-to-a-long-random-secret') {
    $Token = $existing
    Write-Ok 'Using existing token from .env'
    # Opt into browser control if requested and not already recorded.
    if ($InstallBrowser -eq 'true' -and -not (Select-String -Path '.env' -Pattern '^INSTALL_BROWSER=' -Quiet)) {
        Add-Content -Path '.env' -Value 'INSTALL_BROWSER=true' -Encoding ascii
        Write-Ok 'Enabled browser control in .env (browser baked into the image)'
    }
} else {
    # 64 hex chars, like `openssl rand -hex 32`.
    $bytes = New-Object 'byte[]' 32
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    $Token = -join ($bytes | ForEach-Object { $_.ToString('x2') })
    $lines = @(
        '# AndrewOS Docker environment - generated by docker-start.ps1',
        "ACCESS_TOKEN=$Token"
    )
    if ($Port -ne '3001') { $lines += "PORT=$Port" }
    if ($InstallBrowser -eq 'true') { $lines += 'INSTALL_BROWSER=true' }
    # ASCII, no trailing BOM, so the Linux container reads .env cleanly.
    [System.IO.File]::WriteAllLines((Join-Path (Get-Location) '.env'), $lines, (New-Object System.Text.ASCIIEncoding))
    Write-Ok 'Generated a new login token and saved it to .env'
}
if ($InstallBrowser -eq 'true') {
    Write-Host 'Browser control enabled - the build downloads the browser (~400 MB), so the first build takes longer.' -ForegroundColor Yellow
}

# -- 4. Build and start --
Write-Host ''
Write-Info 'Building and starting the container...'
Write-Host 'First build compiles the Rust binary and may take a few minutes.'
Write-Host ''
docker compose up -d --build
if ($LASTEXITCODE -ne 0) { Die 'docker compose failed. See the output above.' }

# -- 5. Wait for health --
Write-Host ''
Write-Host -NoNewline 'Waiting for the server to come up...' -ForegroundColor Cyan
$ready = $false
foreach ($i in 1..30) {
    try {
        Invoke-WebRequest -UseBasicParsing -Uri "http://127.0.0.1:$Port/web" -TimeoutSec 3 | Out-Null
        $ready = $true; break
    } catch { Write-Host -NoNewline '.'; Start-Sleep -Seconds 2 }
}
if ($ready) { Write-Host ' ready!' -ForegroundColor Green } else { Write-Host '' }

# -- Summary --
Write-Host ''
Write-Host '========================================' -ForegroundColor Blue
Write-Host '  AndrewOS is running!'                    -ForegroundColor Green
Write-Host '========================================' -ForegroundColor Blue
Write-Host ''
Write-Host "  Open:   http://localhost:$Port/web/" -ForegroundColor Cyan
Write-Host "  Token:  $Token"                      -ForegroundColor Yellow
Write-Host ''
Write-Host '  (The token is saved in .env - paste it into the web UI to log in,'
Write-Host '   then set your AI provider and API key under Settings.)'
Write-Host ''
if ($InstallBrowser -eq 'true') {
    Write-Host '  Browser control: browser is baked in - enable it in'      -ForegroundColor Green
    Write-Host '  Settings -> AI / API -> Browser Control (engine: Chromium).'
    Write-Host ''
}
Write-Host '  Logs:   docker compose logs -f'
Write-Host '  Stop:   docker compose down'
Write-Host '  Start:  docker compose up -d'
Write-Host ''

Start-Process "http://localhost:$Port/web/" | Out-Null
