//! Bundled agent-team library.
//!
//! Ready-made specialist teams generated from the `awesome-claude-code-subagents`
//! and `awesome-codex-subagents` catalogs: one team per category, each an
//! orchestrator plus that category's specialists, every specialist keeping its
//! original system prompt as its persona.
//!
//! They are embedded in the binary and written into `data/agents/` on first run,
//! matching how bundled skills are installed. An existing file is never
//! overwritten — a team the user has edited is theirs.

use std::path::PathBuf;

use tracing::info;

/// `(filename, contents)` for every bundled team.
macro_rules! bundled_teams {
    ($($file:literal),* $(,)?) => {
        &[$(($file, include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/assets/agents/", $file)))),*]
    };
}

pub const BUNDLED_TEAMS: &[(&str, &str)] = bundled_teams![
    "claude-01-core-development.yaml",
    "claude-02-language-specialists.yaml",
    "claude-03-infrastructure.yaml",
    "claude-04-quality-security.yaml",
    "claude-05-data-ai.yaml",
    "claude-06-developer-experience.yaml",
    "claude-07-specialized-domains.yaml",
    "claude-08-business-product.yaml",
    "claude-09-meta-orchestration.yaml",
    "claude-10-research-analysis.yaml",
    "codex-01-core-development.yaml",
    "codex-02-language-specialists.yaml",
    "codex-03-infrastructure.yaml",
    "codex-04-quality-security.yaml",
    "codex-05-data-ai.yaml",
    "codex-06-developer-experience.yaml",
    "codex-07-specialized-domains.yaml",
    "codex-08-business-product.yaml",
    "codex-09-meta-orchestration.yaml",
    "codex-10-research-analysis.yaml",
    "codex-11-ai-governance-safety.yaml",
    "codex-12-platform-engineering-idp.yaml",
    "codex-13-llmops-evals-observability.yaml",
];

fn agents_dir() -> PathBuf {
    crate::server::data::data_dir().join("agents")
}

/// Write any bundled team that isn't already on disk. Returns how many were
/// installed. Never overwrites: a team the user edited stays edited.
pub async fn install_bundled_teams() -> usize {
    let dir = agents_dir();
    if tokio::fs::create_dir_all(&dir).await.is_err() {
        return 0;
    }
    let mut installed = 0;
    for (name, body) in BUNDLED_TEAMS {
        let path = dir.join(name);
        if path.exists() {
            continue;
        }
        if tokio::fs::write(&path, body).await.is_ok() {
            installed += 1;
        }
    }
    if installed > 0 {
        info!("[init] Installed {} bundled agent teams into {}", installed, dir.display());
    }
    installed
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every bundled team must parse. The YAML is generated by a script, so a
    /// malformed emitter would otherwise only surface when a user picked the
    /// team at runtime.
    #[test]
    fn every_bundled_team_is_valid_yaml_with_the_expected_shape() {
        assert!(!BUNDLED_TEAMS.is_empty(), "no teams were bundled");
        let mut specialists = 0usize;

        for (name, body) in BUNDLED_TEAMS {
            let doc: serde_yaml::Value = serde_yaml::from_str(body)
                .unwrap_or_else(|e| panic!("{name} is not valid YAML: {e}"));

            assert!(
                doc["system"]["name"].as_str().is_some_and(|s| !s.is_empty()),
                "{name}: system.name missing"
            );
            assert_eq!(
                doc["system"]["orchestration_mode"].as_str(),
                Some("hierarchical"),
                "{name}: unexpected orchestration_mode"
            );

            let agents = doc["agents"].as_sequence()
                .unwrap_or_else(|| panic!("{name}: agents is not a list"));
            assert!(agents.len() >= 3, "{name}: expected an orchestrator and workers");

            let mut seen_ids = std::collections::HashSet::new();
            let mut has_orchestrator = false;
            for a in agents {
                let id = a["id"].as_str()
                    .unwrap_or_else(|| panic!("{name}: an agent has no id"));
                assert!(seen_ids.insert(id.to_string()), "{name}: duplicate agent id '{id}'");

                let role = a["role"].as_str()
                    .unwrap_or_else(|| panic!("{name}: agent '{id}' has no role"));
                match role {
                    "orchestrator" => has_orchestrator = true,
                    "worker" => {
                        specialists += 1;
                        // A worker with an empty persona would silently become a
                        // generic agent — the whole point is the imported prompt.
                        assert!(
                            a["persona"].as_str().is_some_and(|p| p.trim().len() > 20),
                            "{name}: worker '{id}' lost its persona"
                        );
                    }
                    "human" => {}
                    other => panic!("{name}: agent '{id}' has unexpected role '{other}'"),
                }
            }
            assert!(has_orchestrator, "{name}: no orchestrator");
        }

        // Guards against the generator silently importing almost nothing.
        assert!(specialists > 300, "expected 300+ specialists, got {specialists}");
    }

    #[test]
    fn both_source_catalogs_are_represented() {
        let has = |p: &str| BUNDLED_TEAMS.iter().any(|(n, _)| n.starts_with(p));
        assert!(has("claude-"), "claude catalog missing");
        assert!(has("codex-"), "codex catalog missing");
    }
}
